name: Deploy Auth Service

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Google Cloud auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Run tests
        run: go test ./...

      - name: Build and deploy to Cloud Run
        run: |
          gcloud run deploy the-forgerealm-auth \
            --source . \
            --region us-central1 \
            --allow-unauthenticated \
            --project ${{ secrets.GCP_PROJECT_ID }} \
            --update-secrets "JWT_SECRET_CURRENT=JWT_SECRET_CURRENT:latest,JWT_SECRET_NEXT=JWT_SECRET_NEXT:latest,PATREON_CLIENT_ID=PATREON_CLIENT_ID:latest,PATREON_CLIENT_SECRET=PATREON_CLIENT_SECRET:latest,WEB_HOOK_SECRET=WEB_HOOK_SECRET:latest,DATABASE_URL=AUTH_DB_URL:latest,PATREON_REDIRECT_URL=PATREON_REDIRECT_URL:latest"
